baseURL = 'https://docs.omega-stream.site/'
languageCode = 'en-us'
title = 'Omegastream Docs'
copyright = '2022 Omegastream'
theme = 'learn'

[params]
  themeVariant = "cust"
  description = "Using Omegastream Docs, you can find the latest Omega documentation for our enterprise API with examples and more than one language."