baseURL = 'https://docs.omega-stream.site/'
languageCode = 'en-us'
title = 'Omegastream Docs'
copyright = '2022 Omegastream'
theme = 'learn'

[params]
  themeVariant = "cust"
  description = "This is the official documentation for Omegastream api, here you will find all the information you need to integrate with Omega api.
"